Change exclusion list; include submodules in hash/timestamp checks

diff --git a/.github/workflows/pre-run-check.yml b/.github/workflows/pre-run-check.yml
--- a/.github/workflows/pre-run-check.yml
+++ b/.github/workflows/pre-run-check.yml
@@ -91,29 +91,30 @@ jobs:
         uses: actions/checkout@v4
         with:
             fetch-depth: 0
+            submodules: 'true'
 
       - name: Gen File List
         run: |
-            find "$GITHUB_WORKSPACE" -type f -name "*.sv" \
-                                          -o -name "*.svh" \
-                                          -o -name "*.rdl" \
-                                          -o -name "*.json" \
-                                          -o -name "*.v" \
-                                          -o -name "*.vh" \
-                                          -o -name "*.rsp" \
-                                          -o -name "*.s" \
-                                          -o -name "*.c" \
-                                          -o -name "*.cpp" \
-                                          -o -name "*.h" \
-                                          -o -name "*.hex" \
-                                          -o -name "*.ld" \
-                                          -o -name "*.gdb" \
-                                          -o -name "*.yml" \
-                                          -o -name "*.sh" \
-                                          -o -name "*.py" \
-                                          -o -name "pr_timestamp" \
-                                          ! -path "*.git/*" | LC_COLLATE=C sort -o $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt
-            sed -i "/third_party/d" $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt
+            find "$GITHUB_WORKSPACE" -type f \( -name "*.sv" \
+                                             -o -name "*.svh" \
+                                             -o -name "*.rdl" \
+                                             -o -name "*.json" \
+                                             -o -name "*.v" \
+                                             -o -name "*.vh" \
+                                             -o -name "*.rsp" \
+                                             -o -name "*.s" \
+                                             -o -name "*.c" \
+                                             -o -name "*.cpp" \
+                                             -o -name "*.h" \
+                                             -o -name "*.hex" \
+                                             -o -name "*.ld" \
+                                             -o -name "*.gdb" \
+                                             -o -name "*.yml" \
+                                             -o -name "*.sh" \
+                                             -o -name "*.py" \
+                                             -o -name "pr_timestamp" \) \
+                                             ! -path "*.github/workflows/*" \
+                                             ! -path "*.git/*" | LC_COLLATE=C sort -o $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt
             sed -i "s,^$GITHUB_WORKSPACE/,," $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt
             echo "Found $(wc -l $GITHUB_WORKSPACE/.github/workflow_metadata/file_list.txt) source code files to hash"
             echo -e "First five files:\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
@@ -122,21 +123,25 @@ jobs:
 
 
       - name: Check Timestamp
+        env:
+            TARGET_BR: ${{ (github.event_name == 'pull_request' && github.base_ref) || (github.event_name == 'workflow_dispatch' && inputs.base_ref) }}
         run: |
             # Find the last commit that modified any design file (not documentation)
             # Start the search with the second parent of the PR merge commit
             # in order to only traverse the feature branch commits
+            # Use an explicit list of files instead of an exclusion list
             last_commit=$(git rev-parse HEAD^2)
-            until git diff --name-only "${last_commit}^..${last_commit}" | grep -v '\.md\|\.png' > /dev/null; do
+            until git diff --name-only "${last_commit}^..${last_commit}" | grep -v '.github/workflows' | grep -e '\.sv\|\.svh\|\.rdl\|\.json\|\.v\|\.vh\|\.rsp\|\.s\|\.c\|\.cpp\|\.h\|\.hex\|\.ld\|\.gdb\|\.yml\|\.sh\|\.py\|pr_timestamp' > /dev/null; do
                 last_commit="$(git rev-parse ${last_commit}^)"
             done
             echo "Latest non-doc hash is ${last_commit}"
-            # If the last non-doc commit is already contained in branch 'main', then skip the
+            echo "Checking if ${last_commit} is contained in branch 'origin/$TARGET_BR'"
+            # If the last non-doc commit is already contained in branch 'TARGET_BR', then skip the
             # timestamp check -- as that commit would already be signed off through another PR.
-            # Otherwise, that commit would fail because it's part of a commit that was squashed into main
+            # Otherwise, that commit would fail because it's part of a commit that was squashed into TARGET_BR
             # much later than the original stamp commit.
-            if [[ $(git branch --remotes --list 'origin/main' --contains ${last_commit}) =~ 'origin/main' ]]; then
-                echo "Commit ${last_commit} is contained in branch 'main', skipping timestamp check"
+            if [[ $(git branch --remotes --list "origin/$TARGET_BR" --contains ${last_commit}) =~ "origin/$TARGET_BR" ]]; then
+                echo "Commit ${last_commit} is contained in branch '$TARGET_BR', skipping timestamp check"
             else
                 # Compare the timestamp from the latest commit with the pr_timestamp file
                 timestamp_exp=$(bc <<< "$(git log -n1 --pretty=tformat:'%ct' ${last_commit})-3600")
