Fix how fork repos are checked out/fetched/compared for compile.yml check

diff --git a/.github/workflows/pre-run-check.yml b/.github/workflows/pre-run-check.yml
--- a/.github/workflows/pre-run-check.yml
+++ b/.github/workflows/pre-run-check.yml
@@ -51,15 +51,29 @@ jobs:
                 exit 0
               fi
             done
+            echo "git fetch origin $TARGET_BR"
+            if ! git fetch origin $TARGET_BR; then
+              echo "git fetch failed\!"
+              exit 1
+            fi
             if [[ "${SOURCE_FORK}" == "true" ]]; then
               echo "pull request is from a fork: ${SOURCE_FORK}"
               echo "fork repository owner is ${SOURCE_OWN}"
               echo "adding remote '${SOURCE_OWN}' at url '${SOURCE_URL}'"
               git remote add -f ${SOURCE_OWN} ${SOURCE_URL}
+              SOURCE_REMOTE=${SOURCE_OWN}
+            else
+              SOURCE_REMOTE=origin
             fi
-            echo "target ref is $(git show-ref origin/${TARGET_BR} 2> /dev/null)"
-            echo "source ref is $(git show-ref ${SOURCE_OWN}/${SOURCE_BR} 2> /dev/null)"
-            compiles=$(git diff --name-only $(git show-ref --hash "origin/$TARGET_BR")...$(git show-ref --hash "${SOURCE_OWN}/${SOURCE_BR}"))
+            echo "git fetch ${SOURCE_REMOTE} $SOURCE_BR"
+            if ! git fetch ${SOURCE_REMOTE} $SOURCE_BR; then
+              echo "git fetch failed\!"
+              exit 1
+            fi
+            echo "target ref for [origin/${TARGET_BR}] is $(git log -n1 --pretty=tformat:'%H' origin/${TARGET_BR} 2> /dev/null)"
+            echo "source ref for [${SOURCE_REMOTE}/${SOURCE_BR}] is $(git log -n1 --pretty=tformat:'%H' ${SOURCE_REMOTE}/${SOURCE_BR} 2> /dev/null)"
+            echo "Comparing $SOURCE_REMOTE/$SOURCE_BR against merge target origin/$TARGET_BR to look for compile.yml"
+            compiles=$(git diff --name-only $(git log -n1 --pretty=tformat:'%H' "origin/$TARGET_BR")...$(git log -n1 --pretty=tformat:'%H' "${SOURCE_REMOTE}/${SOURCE_BR}"))
             if [[ $(grep -c compile.yml <<< "$compiles") -gt 0 ]]; then
                 echo "compile.yml should not be modified for pull requests! Found:"
                 echo "$compiles"
